name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          
          # Create and switch to a new docs branch
          git checkout --orphan docs
          
          # Remove everything except dist directory
          find . -maxdepth 1 ! -name 'dist' ! -name '.git' -exec rm -rf {} +
          
          # Move contents of dist to root
          mv dist/* .
          rm -rf dist
          
          # Add all changes
          git add -A
          git commit -m "Deploy docs for ${{ github.ref_name }}"
          
          # Force push to docs branch
          git push origin docs --force
